name: tasks_app
description: "A new Flutter project."
 
publish_to: 'none' 

 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  lottie: ^2.6.0
  animated_text_kit: ^4.0.0
  introduction_screen: ^3.1.7
  pie_chart: ^5.4.0
  syncfusion_flutter_charts: ^24.2.4+3


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
 
flutter:

  
  uses-material-design: true

   
  assets:
    - assets/1.json
    - assets/2.json
    - assets/3.json
    - assets/girl.jpg


 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  #  